"""Initial candidates rights audit and search cache

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_cache",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("search_cache", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_search_cache_expires_at"), ["expires_at"], unique=False
        )

    op.create_table(
        "video_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_video_id", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("preview_url", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column(
            "orientation",
            sa.Enum(
                "portrait",
                "landscape",
                "square",
                "unknown",
                name="orientation",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("author_url", sa.Text(), nullable=True),
        sa.Column("search_query", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("industrial_process", sa.String(length=200), nullable=True),
        sa.Column("object_being_manufactured", sa.String(length=200), nullable=False),
        sa.Column("visual_score", sa.Float(), nullable=True),
        sa.Column("transformation_score", sa.Float(), nullable=True),
        sa.Column("machine_score", sa.Float(), nullable=True),
        sa.Column("hook_score", sa.Float(), nullable=True),
        sa.Column("loop_score", sa.Float(), nullable=True),
        sa.Column("educational_score", sa.Float(), nullable=True),
        sa.Column("total_score", sa.Float(), nullable=True),
        sa.Column("score_details", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DISCOVERED",
                "SCORED",
                "REJECTED",
                "APPROVED",
                "PROCESSING",
                "READY",
                name="candidate_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "total_score IS NULL OR (total_score >= 0 AND total_score <= 100)",
            name="ck_candidate_total_score",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_video_id", name="uq_candidate_provider_video"),
    )
    with op.batch_alter_table("video_candidates", schema=None) as batch_op:
        batch_op.create_index("ix_candidate_status_score", ["status", "total_score"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_video_candidates_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_video_candidates_industrial_process"),
            ["industrial_process"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_video_candidates_provider"), ["provider"], unique=False
        )

    op.create_table(
        "candidate_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("reviewer", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["video_candidates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("candidate_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_events_candidate_id"), ["candidate_id"], unique=False
        )

    op.create_table(
        "rights_records",
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("creator", sa.Text(), nullable=True),
        sa.Column("license_name", sa.String(length=200), nullable=True),
        sa.Column("license_url", sa.Text(), nullable=True),
        sa.Column("commercial_use_allowed", sa.Boolean(), nullable=True),
        sa.Column("modification_allowed", sa.Boolean(), nullable=True),
        sa.Column("attribution_required", sa.Boolean(), nullable=True),
        sa.Column("attribution_text", sa.Text(), nullable=True),
        sa.Column(
            "rights_status",
            sa.Enum(
                "VERIFIED",
                "UNKNOWN",
                "RESTRICTED",
                "MANUAL_REVIEW_REQUIRED",
                name="rights_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("verification_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.String(length=200), nullable=True),
        sa.Column("evidence_url", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["video_candidates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rights_records")
    with op.batch_alter_table("candidate_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_events_candidate_id"))

    op.drop_table("candidate_events")
    with op.batch_alter_table("video_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_video_candidates_provider"))
        batch_op.drop_index(batch_op.f("ix_video_candidates_industrial_process"))
        batch_op.drop_index(batch_op.f("ix_video_candidates_category"))
        batch_op.drop_index("ix_candidate_status_score")

    op.drop_table("video_candidates")
    with op.batch_alter_table("search_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_cache_expires_at"))

    op.drop_table("search_cache")
    # ### end Alembic commands ###
