"""add technical research dossiers claims and sources

Revision ID: 0003
Revises: 0002
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_dossiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEEDS_REVIEW",
                "VERIFIED",
                "REJECTED",
                name="research_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("detected_object", sa.String(length=300), nullable=True),
        sa.Column("detected_process", sa.String(length=300), nullable=True),
        sa.Column("visual_observations", sa.JSON(), nullable=False),
        sa.Column("alternate_process_hypotheses", sa.JSON(), nullable=False),
        sa.Column("research_questions", sa.JSON(), nullable=False),
        sa.Column("search_queries", sa.JSON(), nullable=False),
        sa.Column("research_summary", sa.Text(), nullable=False),
        sa.Column("verified_process_name", sa.String(length=300), nullable=True),
        sa.Column("process_confidence", sa.Float(), nullable=False),
        sa.Column("material", sa.String(length=300), nullable=True),
        sa.Column("machine_types", sa.JSON(), nullable=False),
        sa.Column("process_steps", sa.JSON(), nullable=False),
        sa.Column("technical_explanations", sa.JSON(), nullable=False),
        sa.Column("interesting_facts", sa.JSON(), nullable=False),
        sa.Column("safety_notes", sa.JSON(), nullable=False),
        sa.Column("unknowns", sa.JSON(), nullable=False),
        sa.Column("search_provider", sa.String(length=60), nullable=False),
        sa.Column("research_provider", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("research_version", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(length=200), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "process_confidence >= 0 AND process_confidence <= 1",
            name="ck_research_process_confidence",
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["video_candidates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("research_dossiers", schema=None) as batch_op:
        batch_op.create_index(
            "ix_research_dossier_candidate_created", ["candidate_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_research_dossier_reuse",
            [
                "candidate_id",
                "search_provider",
                "research_provider",
                "model",
                "prompt_version",
                "research_version",
            ],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_research_dossiers_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_research_dossiers_status"), ["status"], unique=False)

    op.create_table(
        "research_claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "PARTIALLY_SUPPORTED",
                "UNVERIFIED",
                "CONTRADICTED",
                name="claim_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "knowledge_type",
            sa.Enum(
                "OBSERVATION",
                "INFERENCE",
                "VERIFIED_FACT",
                "UNKNOWN",
                name="knowledge_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_support_confidence", sa.Float(), nullable=False),
        sa.Column("video_applicability_confidence", sa.Float(), nullable=False),
        sa.Column("quantitative", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "source_support_confidence >= 0 AND source_support_confidence <= 1",
            name="ck_claim_source_confidence",
        ),
        sa.CheckConstraint(
            "video_applicability_confidence >= 0 AND video_applicability_confidence <= 1",
            name="ck_claim_video_confidence",
        ),
        sa.ForeignKeyConstraint(["dossier_id"], ["research_dossiers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("research_claims", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_research_claims_category"), ["category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_research_claims_dossier_id"), ["dossier_id"], unique=False
        )

    op.create_table(
        "research_contradictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=False),
        sa.Column("claim_ids", sa.JSON(), nullable=False),
        sa.Column("source_ids", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("possible_explanations", sa.JSON(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["dossier_id"], ["research_dossiers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("research_contradictions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_contradictions_dossier_id"), ["dossier_id"], unique=False
        )

    op.create_table(
        "research_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("publisher", sa.String(length=300), nullable=False),
        sa.Column("author", sa.String(length=300), nullable=True),
        sa.Column("publication_date", sa.String(length=80), nullable=True),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "STANDARD",
                "GOVERNMENT",
                "ACADEMIC",
                "MANUFACTURER",
                "INDUSTRY_ASSOCIATION",
                "TECHNICAL_MEDIA",
                "EDUCATIONAL",
                "FORUM_SOCIAL",
                "OTHER",
                name="source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "tier",
            sa.Enum(
                "TIER_A",
                "TIER_B",
                "TIER_C",
                "TIER_D",
                name="source_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("credibility", sa.Float(), nullable=False),
        sa.Column("search_snippet", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.CheckConstraint("credibility >= 0 AND credibility <= 1", name="ck_source_credibility"),
        sa.CheckConstraint("relevance >= 0 AND relevance <= 1", name="ck_source_relevance"),
        sa.ForeignKeyConstraint(["dossier_id"], ["research_dossiers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dossier_id", "url", name="uq_research_source_dossier_url"),
    )
    with op.batch_alter_table("research_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_sources_dossier_id"), ["dossier_id"], unique=False
        )

    op.create_table(
        "research_claim_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column(
            "relation",
            sa.Enum(
                "SUPPORTS",
                "CONTRADICTS",
                "CONTEXT",
                name="evidence_relation",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("location", sa.String(length=500), nullable=False),
        sa.Column("source_says_confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "source_says_confidence >= 0 AND source_says_confidence <= 1",
            name="ck_claim_evidence_confidence",
        ),
        sa.ForeignKeyConstraint(["claim_id"], ["research_claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["research_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("research_claim_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_claim_evidence_claim_id"), ["claim_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_research_claim_evidence_source_id"), ["source_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("research_claim_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_claim_evidence_source_id"))
        batch_op.drop_index(batch_op.f("ix_research_claim_evidence_claim_id"))

    op.drop_table("research_claim_evidence")
    with op.batch_alter_table("research_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_sources_dossier_id"))

    op.drop_table("research_sources")
    with op.batch_alter_table("research_contradictions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_contradictions_dossier_id"))

    op.drop_table("research_contradictions")
    with op.batch_alter_table("research_claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_claims_dossier_id"))
        batch_op.drop_index(batch_op.f("ix_research_claims_category"))

    op.drop_table("research_claims")
    with op.batch_alter_table("research_dossiers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_dossiers_status"))
        batch_op.drop_index(batch_op.f("ix_research_dossiers_candidate_id"))
        batch_op.drop_index("ix_research_dossier_reuse")
        batch_op.drop_index("ix_research_dossier_candidate_created")

    op.drop_table("research_dossiers")
    # ### end Alembic commands ###
