"""add verified script drafts

Revision ID: 0004
Revises: 0003
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "script_drafts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("research_dossier_id", sa.Integer(), nullable=False),
        sa.Column("visual_evaluation_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VALIDATED",
                "NEEDS_REVISION",
                "APPROVED",
                "REJECTED",
                name="script_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "style",
            sa.Enum(
                "EDUCATIONAL",
                "CURIOSITY",
                "PROCESS_EXPLAINER",
                name="script_style",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "target_platform",
            sa.Enum(
                "FACEBOOK_REELS", name="target_platform", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("target_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("estimated_duration_seconds", sa.Float(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("speaking_rate", sa.Float(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("hook", sa.Text(), nullable=False),
        sa.Column("closing", sa.Text(), nullable=False),
        sa.Column("full_narration", sa.Text(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("script_version", sa.String(length=40), nullable=False),
        sa.Column("variant_index", sa.Integer(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("batch_key", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(length=200), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=False),
        sa.CheckConstraint("estimated_duration_seconds > 0", name="ck_script_duration"),
        sa.CheckConstraint("word_count >= 1", name="ck_script_word_count"),
        sa.ForeignKeyConstraint(["candidate_id"], ["video_candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["research_dossier_id"], ["research_dossiers.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["visual_evaluation_id"], ["score_evaluations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("script_drafts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_script_candidate_created", ["candidate_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_script_drafts_batch_key"), ["batch_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_script_drafts_cache_key"), ["cache_key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_script_drafts_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_script_drafts_research_dossier_id"),
            ["research_dossier_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_script_drafts_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_script_drafts_visual_evaluation_id"),
            ["visual_evaluation_id"],
            unique=False,
        )
        batch_op.create_index("ix_script_reuse", ["cache_key", "batch_key"], unique=False)

    op.create_table(
        "script_beats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "HOOK",
                "SETUP",
                "TRANSFORMATION",
                "TECHNICAL_INSIGHT",
                "PAYOFF",
                name="script_beat_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("recommended_start", sa.Float(), nullable=False),
        sa.Column("recommended_end", sa.Float(), nullable=False),
        sa.Column("visual_direction", sa.Text(), nullable=False),
        sa.CheckConstraint("recommended_end > recommended_start", name="ck_beat_interval"),
        sa.ForeignKeyConstraint(["script_id"], ["script_drafts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("script_id", "position", name="uq_script_beat_position"),
    )
    with op.batch_alter_table("script_beats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_script_beats_script_id"), ["script_id"], unique=False)

    op.create_table(
        "script_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("reviewer", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["script_id"], ["script_drafts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("script_reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_script_reviews_script_id"), ["script_id"], unique=False
        )

    op.create_table(
        "script_sentences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("beat_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("display_text", sa.Text(), nullable=False),
        sa.Column("spoken_text", sa.Text(), nullable=False),
        sa.Column(
            "factuality_type",
            sa.Enum(
                "OBSERVATION",
                "VERIFIED_FACT",
                "INFERENCE",
                "EDITORIAL",
                name="script_factuality_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["beat_id"], ["script_beats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("beat_id", "position", name="uq_sentence_position"),
    )
    with op.batch_alter_table("script_sentences", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_script_sentences_beat_id"), ["beat_id"], unique=False)

    op.create_table(
        "script_sentence_claims",
        sa.Column("sentence_id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["research_claims.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sentence_id"], ["script_sentences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sentence_id", "claim_id"),
    )
    op.create_table(
        "script_sentence_visual_refs",
        sa.Column("sentence_id", sa.Integer(), nullable=False),
        sa.Column("visual_ref", sa.String(length=80), nullable=False),
        sa.Column("start", sa.Float(), nullable=False),
        sa.Column("end", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["sentence_id"], ["script_sentences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sentence_id", "visual_ref"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("script_sentence_visual_refs")
    op.drop_table("script_sentence_claims")
    with op.batch_alter_table("script_sentences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_script_sentences_beat_id"))

    op.drop_table("script_sentences")
    with op.batch_alter_table("script_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_script_reviews_script_id"))

    op.drop_table("script_reviews")
    with op.batch_alter_table("script_beats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_script_beats_script_id"))

    op.drop_table("script_beats")
    with op.batch_alter_table("script_drafts", schema=None) as batch_op:
        batch_op.drop_index("ix_script_reuse")
        batch_op.drop_index(batch_op.f("ix_script_drafts_visual_evaluation_id"))
        batch_op.drop_index(batch_op.f("ix_script_drafts_status"))
        batch_op.drop_index(batch_op.f("ix_script_drafts_research_dossier_id"))
        batch_op.drop_index(batch_op.f("ix_script_drafts_candidate_id"))
        batch_op.drop_index(batch_op.f("ix_script_drafts_cache_key"))
        batch_op.drop_index(batch_op.f("ix_script_drafts_batch_key"))
        batch_op.drop_index("ix_script_candidate_created")

    op.drop_table("script_drafts")
    # ### end Alembic commands ###
