"""add narration assets

Revision ID: 0005
Revises: 0004
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voice_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("provider_voice_id", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_voice_id", name="uq_voice_provider_id"),
    )
    with op.batch_alter_table("voice_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_voice_profiles_provider"), ["provider"], unique=False)

    op.create_table(
        "narration_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=False),
        sa.Column("voice_profile_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("voice_settings", sa.JSON(), nullable=False),
        sa.Column("source_text_hash", sa.String(length=64), nullable=False),
        sa.Column("source_character_count", sa.Integer(), nullable=False),
        sa.Column("audio_format", sa.String(length=30), nullable=False),
        sa.Column("codec", sa.String(length=40), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("estimated_duration_seconds", sa.Float(), nullable=False),
        sa.Column("duration_difference_seconds", sa.Float(), nullable=False),
        sa.Column("duration_difference_percent", sa.Float(), nullable=False),
        sa.Column(
            "duration_status",
            sa.Enum(
                "WITHIN_TARGET",
                "TOO_SHORT",
                "TOO_LONG",
                name="narration_duration_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("generation_version", sa.String(length=40), nullable=False),
        sa.Column("provider_metadata", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VALIDATED",
                "NEEDS_REVIEW",
                "APPROVED",
                "REJECTED",
                "FAILED",
                name="narration_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "alignment_method",
            sa.Enum(
                "PROVIDER_ALIGNMENT",
                "ESTIMATED_ALIGNMENT",
                name="narration_alignment_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(length=200), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=False),
        sa.CheckConstraint("duration_seconds > 0", name="ck_narration_duration"),
        sa.CheckConstraint("file_size_bytes > 0", name="ck_narration_file_size"),
        sa.ForeignKeyConstraint(["script_id"], ["script_drafts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["voice_profile_id"], ["voice_profiles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_path"),
    )
    with op.batch_alter_table("narration_assets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_narration_assets_cache_key"), ["cache_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_narration_assets_script_id"), ["script_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_narration_assets_source_text_hash"), ["source_text_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_narration_assets_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_narration_assets_voice_profile_id"), ["voice_profile_id"], unique=False
        )
        batch_op.create_index("ix_narration_reuse", ["cache_key"], unique=False)
        batch_op.create_index(
            "ix_narration_script_created", ["script_id", "created_at"], unique=False
        )

    op.create_table(
        "narration_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("narration_id", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("reviewer", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["narration_id"], ["narration_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("narration_reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_narration_reviews_narration_id"), ["narration_id"], unique=False
        )

    op.create_table(
        "narration_alignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("narration_id", sa.Integer(), nullable=False),
        sa.Column("sentence_id", sa.Integer(), nullable=False),
        sa.Column("beat_id", sa.Integer(), nullable=False),
        sa.Column("start_seconds", sa.Float(), nullable=False),
        sa.Column("end_seconds", sa.Float(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "PROVIDER_ALIGNMENT",
                "ESTIMATED_ALIGNMENT",
                name="narration_alignment_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["beat_id"], ["script_beats.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["narration_id"], ["narration_assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sentence_id"], ["script_sentences.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("narration_id", "sentence_id", name="uq_alignment_sentence"),
    )
    with op.batch_alter_table("narration_alignments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_narration_alignments_beat_id"), ["beat_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_narration_alignments_narration_id"), ["narration_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_narration_alignments_sentence_id"), ["sentence_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("narration_alignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_narration_alignments_sentence_id"))
        batch_op.drop_index(batch_op.f("ix_narration_alignments_narration_id"))
        batch_op.drop_index(batch_op.f("ix_narration_alignments_beat_id"))

    op.drop_table("narration_alignments")
    with op.batch_alter_table("narration_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_narration_reviews_narration_id"))

    op.drop_table("narration_reviews")
    with op.batch_alter_table("narration_assets", schema=None) as batch_op:
        batch_op.drop_index("ix_narration_script_created")
        batch_op.drop_index("ix_narration_reuse")
        batch_op.drop_index(batch_op.f("ix_narration_assets_voice_profile_id"))
        batch_op.drop_index(batch_op.f("ix_narration_assets_status"))
        batch_op.drop_index(batch_op.f("ix_narration_assets_source_text_hash"))
        batch_op.drop_index(batch_op.f("ix_narration_assets_script_id"))
        batch_op.drop_index(batch_op.f("ix_narration_assets_cache_key"))

    op.drop_table("narration_assets")
    with op.batch_alter_table("voice_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_voice_profiles_provider"))

    op.drop_table("voice_profiles")
    # ### end Alembic commands ###
