"""add video edit plans and render assets

Revision ID: 0006
Revises: 0005
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_edit_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=False),
        sa.Column("narration_id", sa.Integer(), nullable=False),
        sa.Column(
            "target_platform",
            sa.Enum(
                "FACEBOOK_REELS",
                name="edit_plan_target_platform",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("aspect_ratio", sa.String(length=20), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("fps", sa.Float(), nullable=False),
        sa.Column("target_duration", sa.Float(), nullable=False),
        sa.Column("actual_narration_duration", sa.Float(), nullable=False),
        sa.Column(
            "composition",
            sa.Enum(
                "CENTER_CROP",
                "FIT",
                "BLURRED_BACKGROUND",
                name="composition_strategy",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_audio_policy",
            sa.Enum("MUTED", name="source_audio_policy", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("audio_configuration", sa.JSON(), nullable=False),
        sa.Column("render_configuration", sa.JSON(), nullable=False),
        sa.Column("planner_version", sa.String(length=40), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("target_duration > 0", name="ck_edit_plan_duration"),
        sa.ForeignKeyConstraint(["candidate_id"], ["video_candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["narration_id"], ["narration_assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["script_id"], ["script_drafts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("video_edit_plans", schema=None) as batch_op:
        batch_op.create_index(
            "ix_edit_plan_candidate_created", ["candidate_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_edit_plan_reuse", ["cache_key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_video_edit_plans_cache_key"), ["cache_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_video_edit_plans_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_video_edit_plans_narration_id"), ["narration_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_video_edit_plans_script_id"), ["script_id"], unique=False
        )

    op.create_table(
        "edit_segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("edit_plan_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("source_start", sa.Float(), nullable=False),
        sa.Column("source_end", sa.Float(), nullable=False),
        sa.Column("output_start", sa.Float(), nullable=False),
        sa.Column("output_end", sa.Float(), nullable=False),
        sa.Column("playback_speed", sa.Float(), nullable=False),
        sa.Column(
            "composition",
            sa.Enum(
                "CENTER_CROP",
                "FIT",
                "BLURRED_BACKGROUND",
                name="edit_segment_composition_strategy",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("beat_id", sa.Integer(), nullable=False),
        sa.Column("sentence_ids", sa.JSON(), nullable=False),
        sa.Column("visual_refs", sa.JSON(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "transition",
            sa.Enum("CUT", name="edit_transition_type", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("loop_count", sa.Integer(), nullable=False),
        sa.Column("hold_seconds", sa.Float(), nullable=False),
        sa.CheckConstraint("hold_seconds >= 0", name="ck_edit_segment_hold"),
        sa.CheckConstraint("loop_count >= 1", name="ck_edit_segment_loop_count"),
        sa.CheckConstraint("output_end > output_start", name="ck_edit_segment_output_interval"),
        sa.CheckConstraint("playback_speed > 0", name="ck_edit_segment_speed"),
        sa.CheckConstraint("source_end > source_start", name="ck_edit_segment_source_interval"),
        sa.ForeignKeyConstraint(["beat_id"], ["script_beats.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["edit_plan_id"], ["video_edit_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("edit_plan_id", "position", name="uq_edit_segment_position"),
    )
    with op.batch_alter_table("edit_segments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_edit_segments_beat_id"), ["beat_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_edit_segments_edit_plan_id"), ["edit_plan_id"], unique=False
        )

    op.create_table(
        "render_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=False),
        sa.Column("narration_id", sa.Integer(), nullable=False),
        sa.Column("edit_plan_id", sa.Integer(), nullable=False),
        sa.Column("output_path", sa.String(length=500), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("fps", sa.Float(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("planned_duration", sa.Float(), nullable=False),
        sa.Column("duration_difference", sa.Float(), nullable=True),
        sa.Column("video_codec", sa.String(length=80), nullable=True),
        sa.Column("audio_codec", sa.String(length=80), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("render_version", sa.String(length=40), nullable=False),
        sa.Column("ffmpeg_version", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RENDERING",
                "VALIDATED",
                "NEEDS_REVIEW",
                "APPROVED",
                "REJECTED",
                "FAILED",
                name="render_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=False),
        sa.Column("process_exit_code", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(length=200), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["video_candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["edit_plan_id"], ["video_edit_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["narration_id"], ["narration_assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["script_id"], ["script_drafts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("output_path"),
    )
    with op.batch_alter_table("render_assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_render_assets_cache_key"), ["cache_key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_render_assets_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_render_assets_edit_plan_id"), ["edit_plan_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_render_assets_narration_id"), ["narration_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_render_assets_script_id"), ["script_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_render_assets_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_render_candidate_created", ["candidate_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_render_reuse", ["cache_key"], unique=False)

    op.create_table(
        "render_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("render_id", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("reviewer", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["render_id"], ["render_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("render_reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_render_reviews_render_id"), ["render_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("render_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_render_reviews_render_id"))

    op.drop_table("render_reviews")
    with op.batch_alter_table("render_assets", schema=None) as batch_op:
        batch_op.drop_index("ix_render_reuse")
        batch_op.drop_index("ix_render_candidate_created")
        batch_op.drop_index(batch_op.f("ix_render_assets_status"))
        batch_op.drop_index(batch_op.f("ix_render_assets_script_id"))
        batch_op.drop_index(batch_op.f("ix_render_assets_narration_id"))
        batch_op.drop_index(batch_op.f("ix_render_assets_edit_plan_id"))
        batch_op.drop_index(batch_op.f("ix_render_assets_candidate_id"))
        batch_op.drop_index(batch_op.f("ix_render_assets_cache_key"))

    op.drop_table("render_assets")
    with op.batch_alter_table("edit_segments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_edit_segments_edit_plan_id"))
        batch_op.drop_index(batch_op.f("ix_edit_segments_beat_id"))

    op.drop_table("edit_segments")
    with op.batch_alter_table("video_edit_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_video_edit_plans_script_id"))
        batch_op.drop_index(batch_op.f("ix_video_edit_plans_narration_id"))
        batch_op.drop_index(batch_op.f("ix_video_edit_plans_candidate_id"))
        batch_op.drop_index(batch_op.f("ix_video_edit_plans_cache_key"))
        batch_op.drop_index("ix_edit_plan_reuse")
        batch_op.drop_index("ix_edit_plan_candidate_created")

    op.drop_table("video_edit_plans")
    # ### end Alembic commands ###
